Repository DevBuffProject/devbuff-frontend, pull requests merged in 2021-01, with the labels that each got.

#247 feat(skill-picker): Скорректировал компонент выбора скиллов #25
  components/Button/Button.vue
  components/Card/Card.vue
  components/Ideas/IdeaCard.vue
  components/SpecialistPicker/SpecialistPicker.vue
  package-lock.json
  pages/ideas/index.vue
  pages/index.vue
  pages/s/dashboard.vue
  pages/s/editor.vue
  static/logos/Logo-white.svg
  store/ideas.js
Labels: feature

#252 feat(input): #248 Валидация в компонентах инпутов
  components/Input/Input.stories.js
  components/Input/Input.vue
  nuxt.config.js
  package-lock.json
  package.json
  plugins/vee-validate.js
Labels: feature

#255 feat(editor): #248 добавил валидацию в редакторе
  components/Editor/Editor.vue
  components/Input/Input.stories.js
  components/Input/Input.vue
  components/SpecialistPicker/SpecialistPicker.vue
  lang/en.js
  lang/ru.js
  nuxt.config.js
  pages/s/editor.vue
  plugins/vee-validate.js
Labels: feature

#262 Improve filter idea
  pages/ideas/index.vue
Labels: feature

#261 feat(components): Новый quill редактор
  assets/styles/common.scss
  assets/styles/typography.scss
  assets/styles/variables.scss
  components/Chip/Chip.vue
  components/Editor/Editor.vue
  components/Editor/old.vue
  components/Editor/v2.vue
  components/Input/Input.stories.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/ideas/_id.vue
  pages/s/editor.vue
Labels: feature

#265 New editor
  components/Editor/Editor.vue
  components/Editor/assets/Blots/twitter-blot/index.js
  components/Ideas/IdeaCard.vue
  components/Input/Input.vue
  components/SpecialistPicker/SpecialistPicker.vue
  components/Tooltip/Tooltip.vue
  endpoints/twitter-embed.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/s/editor.vue
Labels: feature

#268 fix: Рефакторинг и ссылка навигации назад в тулбаре
  assets/styles/common.scss
  assets/styles/typography.scss
  components/Button/Button.vue
  components/Editor/Editor.vue
  components/Editor/content.scss
  components/Editor/old.vue
  components/Editor/v2.vue
  components/Header/Header.vue
  components/Input/Input.vue
  components/Label/Label.vue
  components/OpenGraph/OGPreview.vue
  components/Toolbar/Toolbar.vue
  components/Tooltip/Tooltip.vue
  layouts/default.vue
  pages/ideas/_id.vue
  pages/ideas/index.vue
  pages/index.vue
  pages/s/editor.vue
  pages/s/profile/_id.vue
Labels: service

#270 feat(directives): Добавил material ripple директиву
  assets/styles/common.scss
  assets/vendor/quill/index.js
  assets/vendor/quill/vendor/blot-formatter/index.js
  components/Button/Button.vue
  components/Toolbar/Toolbar.vue
  directives/Ripple/index.js
  directives/Ripple/styles.scss
  directives/index.js
  pages/ideas/index.vue
  plugins/ui-setup.js
Labels: design

#271 Fix #266
  pages/ideas/_id.vue
Labels: bug

#267 Добавил возможность изменения специалистов и заголовка при редактировании идеи
  components/SpecialistPicker/SpecialistPicker.stories.js
  components/SpecialistPicker/SpecialistPicker.vue
  lang/common/specializations.js
  package-lock.json
  package.json
  pages/s/editor.vue
Labels: feature

#272 Editor blot formatter
  assets/vendor/quill/blots/TwitterBlot/index.js
  assets/vendor/quill/index.js
  assets/vendor/quill/vendor/BlotFormatter/actions/AlignAction.js
  assets/vendor/quill/vendor/BlotFormatter/actions/DeleteAction.js
  assets/vendor/quill/vendor/BlotFormatter/actions/ResizeAction.js
  assets/vendor/quill/vendor/BlotFormatter/actions/index.js
  assets/vendor/quill/vendor/BlotFormatter/index.js
  assets/vendor/quill/vendor/BlotFormatter/specs/ImageSpec.js
  assets/vendor/quill/vendor/BlotFormatter/specs/TwitterSpec.js
  assets/vendor/quill/vendor/BlotFormatter/specs/VideoSpec.js
  assets/vendor/quill/vendor/BlotFormatter/specs/index.js
  assets/vendor/quill/vendor/blot-formatter/index.js
  components/Editor/Editor.vue
  directives/Ripple/index.js
  pages/s/editor.vue
Labels: feature, refactor
